In [1]:
import numpy as np
arr1 = np.array([2,4,6,8])
arr2 = np.array([3,6,9,9])
#addition
result1 = arr1+arr2
print(result1)

[ 5 10 15 17]

In [2]:
a1= np.array([10,20,30,40])
a2 = np.array([5,10,15,20])
result4 = a1/a2
print(result4)

[2. 2. 2. 2.]

In [3]:
#mathematical funtions
a = np.array([2,4,6,8])
b = np.array([2,2,2,2])
print(np.power(a,b))

[ 4 16 36 64]

In [4]:
#manipulation funtions
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.reshape(5,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

In [5]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]

In [6]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a.transpose())

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

In [7]:
print('flaten:' , a.flatten())

flaten: [ 1  2  3  4  5  6  7  8  9 10]

In [8]:
a = ([1,2,3,4,5,6,7,8,9,10,11,20])
print("median:" , np.median(a))
print("mean:" , np.mean(a))
print("std:" , np.std(a))
print("var:" , np.var(a))
print("min:" , np.min(a))
print("max:" , np.max(a))
print("percentile:" , np.percentile(a,20))

median: 6.5
mean: 7.166666666666667
std: 4.913134324327891
var: 24.138888888888886
min: 1
max: 20
percentile: 3.2

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

2
(2, 3)
6
int64
8

In [10]:
np.save("data.npy", arr)

In [11]:
L = np.load("data.npy")
print(L)

[[1 2 3]
 [4 5 6]]

In [12]:
arr1 = ([[13,57,] , [11,77]])
result = np.mean(arr1)
result1 = np.mean(arr1 , axis =0)
result2 = np.mean(arr1 , axis =1)
print("enitre array:", result)
print("enitre array along vertical axis :" ,result1)
print("along horizontal axis:" ,result2)

enitre array: 39.5
enitre array along vertical axis : [12. 67.]
along horizontal axis: [35. 44.]

In [13]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]

In [14]:
print(a[2])        # Access single element
print(a[1:4])      # Slice elements from index 1 to 3

3
[2 3 4]

In [15]:
b = np.append(a, 6)
print(b)

[1 2 3 4 5 6]

In [16]:
c = np.delete(a, 2)   # Deletes element at index 2
print(c)

[1 2 4 5]

In [17]:
d = np.sort(a)
print(d)

[1 2 3 4 5]

In [18]:
#matrix 
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A)
C = A + B
print(C)
D = A - B
print(D)
E = np.dot(A, B)
# OR
E = A @ B

print(E)
T = A.T
print(T)

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]

In [19]:
#dictionary
student = {
    "name": "Mukund",
    "age": 21,
    "course": "BCA"
}

print(student)
print(student["name"])        # Using key
print(student.get("age"))     # Using get()

{'name': 'Mukund', 'age': 21, 'course': 'BCA'}
Mukund
21

In [21]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 32, 18, 47, 33],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney']
}
df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47     Tokyo
4      Eve   33    Sydney

In [22]:
# access a single row
single_row = df.loc[2]
print("Single row:", single_row)
print()

# access rows 0, 3 and 4
row_list = df.loc[[0, 3, 4]]
print("List of Rows:", row_list)
print()


# access a list of columns
column_list = df.loc[:, ['Name', 'Age']]
print("List of Columns:", column_list)
print()


# access second row of 'Name' column
specific_value = df.loc[1, 'Name']
print("Specific Value:", specific_value)

Single row: Name    Charlie
Age          18
City     London
Name: 2, dtype: object

List of Rows:     Name  Age      City
0  Alice   25  New York
3  David   47     Tokyo
4    Eve   33    Sydney

List of Columns:       Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47
4      Eve   33

Specific Value: Bob

In [23]:
df = pd.DataFrame(data)
df.iloc[:, 0:2]
df.iloc[0:2, 1:3]

   Age      City
0   25  New York
1   32     Paris

In [27]:
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
dfd=pd.DataFrame(data)
dfd
df2=dfd.assign(Height=[5.9, 5.6, 5.8 , 5.7])
df2
dfd.insert(1, "Address",['Bengaluru', 'Hubli', 'Hydrabad', 'Pune'], 
           allow_duplicates=True)
dfd
df2

    Name  Age    Address  Height
0   John   23  Bengaluru     5.9
1  Henry   34      Hubli     5.6
2   Jack   25   Hydrabad     5.8
3   Mary   27       Pune     5.7

In [30]:
#Adding Rows Using Concat()
#create the first data frame
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
df1=pd.DataFrame(data)

#create the second data frame
data1= {'Name': ['Jimmy', 'Herry'],
      'Age':[33, 34], 
      "Qualification":['MCA', 'BE']}
df2=pd.DataFrame(data1)

df3=pd.concat([df1,df2], axis=1)
df3

    Name  Age    Address   Name   Age Qualification
0   John   23  Bengaluru  Jimmy  33.0           MCA
1  Henry   34      Hubli  Herry  34.0            BE
2   Jack   25   Hydrabad    NaN   NaN           NaN
3   Mary   27       Pune    NaN   NaN           NaN

In [31]:
df4=pd.concat([df1,df2], axis=0)
df4

    Name  Age    Address Qualification
0   John   23  Bengaluru           NaN
1  Henry   34      Hubli           NaN
2   Jack   25   Hydrabad           NaN
3   Mary   27       Pune           NaN
0  Jimmy   33        NaN           MCA
1  Herry   34        NaN            BE

In [33]:
df4.drop(["Address", "Qualification"], axis=1)
df4

    Name  Age    Address Qualification
0   John   23  Bengaluru           NaN
1  Henry   34      Hubli           NaN
2   Jack   25   Hydrabad           NaN
3   Mary   27       Pune           NaN
0  Jimmy   33        NaN           MCA
1  Herry   34        NaN            BE

In [34]:
#droping rows by index label
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
df1=pd.DataFrame(data)
# Setting the index to 'Name'
df1.set_index('Name', inplace=True)
# dropping the rows mentioned
df1.drop(['Henry'], inplace=True)
df1

      Age    Address
Name
John   23  Bengaluru
Jack   25   Hydrabad
Mary   27       Pune

In [35]:
# Sorting the Data farme, here na_position= 'last' moves 
#the rows contatining the NA values to the last and sort the remaining rows
df1.sort_values("Name", axis=0, inplace=True, ascending = False, na_position='last');
df1

      Age    Address
Name
Mary   27       Pune
John   23  Bengaluru
Jack   25   Hydrabad

In [36]:
#Grouping the data
# groupby() method can be used. Python allows to compute aggreagations such as sum(), mean(), median()
#min(), max() on the gropued data
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary', 'Mary', 'Joseph'],
      'Age':[23, 34, 25, 27, 32, 40], 
      'Address':['Bengaluru', 'Hubli', 'Hydrabad', 'Pune', 'Bengaluru', 'Pune'],
      'Salary': [25000, 32000, 56000, 100000, 45000, 120000]}
df1=pd.DataFrame(data)
#calculating the mean salary grouped by address
age_group=df1['Age'].groupby(df1['Address'])

print(age_group.mean())

Address
Bengaluru    27.5
Hubli        34.0
Hydrabad     25.0
Pune         33.5
Name: Age, dtype: float64

In [37]:
import pandas as pd 
import numpy as np
# Creating empty series 
ser = pd.Series() 
print("Pandas Series: ", ser) 

# simple array 
data = np.array(['P', 'G', 'M', 'C', 'A'])   
ser = pd.Series(data) 
print("Pandas Series:\n", ser)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    P
1    G
2    M
3    C
4    A
dtype: object

In [38]:
'''Creating a series from array with an index: In order to create a series by explicitly providing 
index instead of the default, we have to provide a list of elements to the index parameter with 
the same number of elements as it is an array. '''
# import pandas as pd
import pandas as pd

# import numpy as np
import numpy as np

# simple array
data = np.array(['P', 'G', 'M', 'C', 'A'])

# providing an index
ser = pd.Series(data, index=[10, 11, 12, 13, 14])
print(ser)

10    P
11    G
12    M
13    C
14    A
dtype: object

In [39]:
'''Creating a series from array with an index: In order to create a series by explicitly providing 
index instead of the default, we have to provide a list of elements to the index parameter with 
the same number of elements as it is an array. '''
# import pandas as pd
import pandas as pd

# import numpy as np
import numpy as np

# simple array
data = np.array(['P', 'G', 'M', 'C', 'A'])

# providing an index
ser = pd.Series(data, index=[10, 11, 12, 13, 14])
print(ser)

10    P
11    G
12    M
13    C
14    A
dtype: object

In [40]:
#Method2: Using scipy.stats()
import pandas as pd
import scipy
from scipy import stats
# Creating the data frame
details = {
'col1': [1, 3, 5, 7, 9],
'col2': [7, 4, 35, 14, 56]
}
# creating a Dataframe object
df = pd.DataFrame(details)
# Z-Score using scipy
df['col2'] = stats.zscore(df['col2'])
df

   col1      col2
0     1 -0.824387
1     3 -0.977052
2     5  0.600480
3     7 -0.468171
4     9  1.669130